version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - AWS_REGION=eu-central-1
      - S3_BUCKET=minitube-videos-test
    volumes:
      - ./backend:/app